### ISSUE TITLE
Error when sending funds without the decimal point

### ISSUE THREAD

**Issue by tibonova** [steemit/sc2#2]
**What I wanted** 
I wanted to send some SBD to an account via Busy. 
(I'm making the issue here because the URL was steemjs.com when the problem happened.)

**What happened**
I've got an error message.
![Sending SBD error](http://www.steemimg.com/images/2017/02/26/fefb8227e6b8c10bcf7a89097316b9a7.png)

**How to reproduce**
Send integer SBD to an account. 

(As a non-native speaker I don't know if it's the correct term for a number without decimal point. What is important here that try to send e.g. `1` SBD, not `1.000` SBD. You wouldn't have problem the latter, only with the former one.)

**Comment by bonustrack** [comment]
This issue has been solved.
